# Use a friendly name.
name: Release

# Trigger on specific conditions.
on:

  # When manually triggered.
  workflow_dispatch:

# Perform these operations.
jobs:

  # Build and deploy a new release.
  deploy:
    runs-on: ubuntu-latest

    # But only if this is the master branch.
    if: ${{ github.ref == 'refs/heads/main' }}

    # Specify permissions needed.
    permissions:
      contents: write
      pull-requests: write
      packages: write

    # Publish a new image and generate the README.
    steps:
      - uses: actions/checkout@v3

      - name: Publish Image
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate README Pull Request
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false
          branch=automated-documentation-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated documentation update'
          # Add / update and commit
          git add */**/README.md
          git commit -m 'Automated documentation update [skip ci]' || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
          fi
