# Use a friendly name.
name: Test Features

# Trigger on specific conditions.
on:

  # When a change is pushed to main.
  push:
    branches:
      - main

  # For all pull request activity.
  pull_request:

  # When manually triggered.
  workflow_dispatch:

# Perform these operations.
jobs:

  # Runs the default tests for each feature.
  default-tests:
    runs-on: ubuntu-latest

    # Allow all scenario builds to be attempted.
    continue-on-error: true

    # List the features and container images to test.
    strategy:
      matrix:
        features:
          - env
        baseImage:
          - debian:latest
          - ubuntu:latest
          - mcr.microsoft.com/devcontainers/base:ubuntu

    # Generate the test scenarios.
    steps:
      - uses: actions/checkout@v3

      - name: "Installing @devcontainers/cli from NPM"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: |
          devcontainer features test \
            --skip-scenarios \
            -f ${{ matrix.features }} \
            -i ${{ matrix.baseImage }} \
            .

  # Run the test scenarios for each feature.
  scenario-tests:
    runs-on: ubuntu-latest

    # If one scenario fails, allow the others to be attempted.
    continue-on-error: true

    # List the features to be sted.
    strategy:
      matrix:
        features:
          - env

    # Run the tests.
    steps:
      - uses: actions/checkout@v3

      - name: "Installing @devcontainers/cli from NPM"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ matrix.features }}' scenarios"
        run: |
          devcontainer features test \
            -f ${{ matrix.features }} \
            --skip-autogenerated \
            --skip-duplicated \
            .

  # Run the global tests.
  global-tests:
    runs-on: ubuntu-latest

    # Allow testing to continue on error.
    continue-on-error: true

    # Run the tests.
    steps:
      - uses: actions/checkout@v3

      - name: "Installing @devcontainers/cli from NPM"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
